#!/usr/bin/env bash
# Configure custom Nginx response header to track HTTP requests to web servers
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
sed -i '/^\tserver_name.*/a \\trewrite ^/redirect_me https://treasureglobalconcept.com.ng/ permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/error404.html
sed -i '/^\tserver_name.*/a \\terror_page 404 /error404.html;\n\tlocation = /error404.html {\n\troot /var/www/html/;\n\tinternal;\n\t}' /etc/nginx/sites-available/default
sed -i '/^http {.*/a \\tadd_header X-Served-By '"${HOSTNAME}"';' /etc/nginx/nginx.conf
sed -i '/^server {.*/a \\tadd_header X-Served-By '"${HOSTNAME}"';' /etc/nginx/sites-available/default
service nginx restart 
